name: CI
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install modules
              run: npm install
            - name: Check formatting
              run: npx prettier . --check
            - name: Run tests
              run: npm run test
