name: Code Coverage

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
            - uses: actions/checkout@v4

            - name: Install dependencies
              run: npm install

            - name: Check format
              run: npx prettier . --check

            - name: Run tests
              run: npx jest --coverage

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v3
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
