name: CI
on: push
jobs:
    CI:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: npm install
            - name: Check format
              run: npx prettier . --check
            - name: Run tests
              run: npx vitest --coverage
            - name: Report coverage
              if: always()
              uses: davelosert/vitest-coverage-report-action@v2
