name: Generate Docs and Calculate Coverage

on:
    push:
        branches: [main]
    # TODO(#3): Delete this once the PR is merged
    pull_request:
        branches: [main, fix-docs]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Dependencies
              run: npm clean-install

            - name: Generate Documentation
              run: |
                  npm run typedoc
                  # See: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#example-of-a-multiline-string
                  {
                    echo 'LOGO_SVG<<EOF'
                    cat docs/coverage.svg; echo
                    echo EOF
                  } >> "$GITHUB_ENV"

            - name: Upload Badge
              uses: exuanbo/actions-deploy-gist@v1
              with:
                  token: ${{ secrets.GIST_SECRET }}
                  gist_id: ${{ vars.GIST_ID }}
                  file_path: docs/coverage.svg
