name: Generate Docs and Calculate Coverage

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Dependencies
              run: npm clean-install

            - name: Generate Documentation
              run: |
                  npm run typedoc
                  echo 'LOGO_SVG="$(cat build/coverage.svg)"' >> $GITHUB_ENV

            - name: Generate Badge
              uses: schneegans/dynamic-badges-action@v1.7.0
              with:
                  auth: ${{ secrets.GIST_SECRET }}
                  logoSvg: ${{ env.LOGO_SVG }}
                  gistID: ${{ vars.GIST_ID }}
                  filename: coverage.svg
