name: Generate Docs and Calculate Coverage

on:
    push:
        branches:
            - main
    # TODO(#3): Delete this once the PR is merged
    pull_request:
        branches:
            - fix-docs

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Dependencies
              run: npm clean-install

            - name: Generate Documentation
              run: npm run typedoc

            - name: Upload Badge
              uses: actions/upload-artifact@v4
              with:
                  name: docs-coverage-badge
                  path: docs/coverage.svg

            - name: Download Badge
              uses: actions/download-artifact@v4
              with:
                  name: docs-coverage-badge
