name: Generate Docs and Calculate Coverage

on:
    push:
        branches: [main]
    # TODO(#3): Delete this once the PR is merged
    pull_request:
        branches: [main, fix-docs]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Dependencies
              run: npm clean-install

            - name: Generate Documentation
              run: |
                  npm run typedoc
                  {
                    echo 'LOGO_SVG<<EOF'
                    cat docs/coverage.svg | base64
                    echo EOF
                  } >> "$GITHUB_ENV"

            - name: Generate Badge
              uses: schneegans/dynamic-badges-action@v1.7.0
              with:
                  auth: ${{ secrets.GIST_SECRET }}
                  logoSvg: ${{ env.LOGO_SVG }}
                  gistID: ${{ vars.GIST_ID }}
                  filename: coverage.svg
