name: Generate Docs and Calculate Coverage

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Dependencies
              run: npm clean-install

            - name: Generate Documentation
              run: |
                  npm run typedoc
                  {
                    printf "LOGO_SVG<<EOF\n"
                    cat docs/coverage.svg
                    printf "\nEOF"
                  } >> $GITHUB_ENV

            - name: Upload Badge
              uses: exuanbo/actions-deploy-gist@v1
              with:
                  token: ${{ secrets.GIST_SECRET }}
                  gist_id: ${{ vars.GIST_ID }}
                  file_path: docs/coverage.svg
